# Import Dependencies

In [4]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [5]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/WeatherPy_challenge.csv")
city_data_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3hrs),Snow inches (last 3hrs)
0,0,Shingu,JP,2020-05-08 15:50:22,33.73,135.98,56.97,83,100,2.91,overcast clouds,0.0,0
1,1,Niquelandia,BR,2020-05-08 15:50:22,-14.47,-48.46,83.41,57,32,4.83,scattered clouds,0.0,0
2,2,Sioux Lookout,CA,2020-05-08 15:50:22,50.10,-91.92,28.40,54,75,12.75,broken clouds,0.0,0
3,3,Ostrovnoy,RU,2020-05-08 15:46:05,68.05,39.51,34.70,93,97,9.51,overcast clouds,0.0,0
4,4,Punta Arenas,CL,2020-05-08 15:50:23,-53.15,-70.92,42.80,93,81,9.17,broken clouds,0.0,0
5,5,Yabrud,SY,2020-05-08 15:50:23,33.97,36.66,86.00,17,96,11.41,overcast clouds,0.0,0
6,6,Kariba,ZW,2020-05-08 15:50:23,-16.52,28.80,71.40,60,0,3.13,clear sky,0.0,0
7,7,Airai,TL,2020-05-08 15:50:23,-8.93,125.41,56.53,84,7,3.13,clear sky,0.0,0
8,8,Usinsk,RU,2020-05-08 15:50:23,65.99,57.53,36.99,93,100,6.85,overcast clouds,0.0,0
9,9,Bluff,NZ,2020-05-08 15:50:23,-46.60,168.33,49.71,85,47,11.92,scattered clouds,0.0,0

In [6]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [7]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [8]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [22]:
# Ask the customer to add a preference of raining or not.
raining = input("Do you want it to be raining? (yes/no) ")

Do you want it to be raining? (yes/no) no

In [23]:
# Ask the customer to add a preference of snowing or not.
snowing = input("Do you want it to be snowing? (yes/no) ")

Do you want it to be snowing? (yes/no) no

In [24]:
if raining == 'no' and snowing == 'no':
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                           (city_data_df["Max Temp"] >= min_temp) & \
                                           (city_data_df["Rain inches (last 3hrs)"] == 0) & \
                                           (city_data_df["Snow inches (last 3hrs)"] == 0)]

elif raining == 'yes' and snowing == 'yes':
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                           (city_data_df["Max Temp"] >= min_temp) & \
                                           (city_data_df["Rain inches (last 3hrs)"] != 0) & \
                                           (city_data_df["Snow inches (last 3hrs)"] != 0)]

elif raining == 'yes' and snowing == 'no':
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) &\
                                          (city_data_df["Max Temp"] >= min_temp) &\
                                          (city_data_df["Rain inches (last 3hrs)"] != 0) &\
                                          (city_data_df["Snow inches (last 3hrs)"] == 0)]


else:
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) &\
                                          (city_data_df["Max Temp"] >= min_temp) &\
                                          (city_data_df["Rain inches (last 3hrs)"] == 0) & \
                                          (city_data_df["Snow inches (last 3hrs)"] != 0)]

preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3hrs),Snow inches (last 3hrs)
1,1,Niquelandia,BR,2020-05-08 15:50:22,-14.47,-48.46,83.41,57,32,4.83,scattered clouds,0.0,0
5,5,Yabrud,SY,2020-05-08 15:50:23,33.97,36.66,86.00,17,96,11.41,overcast clouds,0.0,0
11,11,Hermanus,ZA,2020-05-08 15:50:24,-34.42,19.23,77.00,50,0,3.00,clear sky,0.0,0
16,16,Bengkulu,ID,2020-05-08 15:50:25,-3.80,102.27,77.40,86,100,5.08,overcast clouds,0.0,0
21,21,Victoria,HK,2020-05-08 15:47:17,22.29,114.16,82.00,84,0,8.63,clear sky,0.0,0
22,22,Guebwiller,FR,2020-05-08 15:50:25,47.92,7.20,82.40,28,89,5.82,overcast clouds,0.0,0
38,38,Sao Filipe,CV,2020-05-08 15:50:28,14.90,-24.50,75.20,72,99,13.11,overcast clouds,0.0,0
41,41,Chumphon,TH,2020-05-08 15:50:28,10.33,98.83,78.15,91,98,0.87,overcast clouds,0.0,0
42,42,Arraial Do Cabo,BR,2020-05-08 15:50:29,-22.97,-42.03,75.20,69,75,10.29,broken clouds,0.0,0
45,45,Vilhena,BR,2020-05-08 15:47:35,-12.74,-60.15,76.73,59,11,5.08,few clouds,0.0,0

# Make Markers for vacation location

In [25]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp","Current Description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Niquelandia,BR,83.41,scattered clouds,-14.47,-48.46,
5,Yabrud,SY,86.00,overcast clouds,33.97,36.66,
11,Hermanus,ZA,77.00,clear sky,-34.42,19.23,
16,Bengkulu,ID,77.40,overcast clouds,-3.80,102.27,
21,Victoria,HK,82.00,clear sky,22.29,114.16,
22,Guebwiller,FR,82.40,overcast clouds,47.92,7.20,
38,Sao Filipe,CV,75.20,overcast clouds,14.90,-24.50,
41,Chumphon,TH,78.15,overcast clouds,10.33,98.83,
42,Arraial Do Cabo,BR,75.20,broken clouds,-22.97,-42.03,
45,Vilhena,BR,76.73,few clouds,-12.74,-60.15,

In [28]:
# Set the parameters to search for hotels.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key}

In [29]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [36]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} {Max Temp}  °F</dd>
</dl>
"""

In [37]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [38]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp,0) for temp in max_temp],
                                 dissipating=False, max_intensity=300, point_radius=4)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [33]:
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Niquelandia,BR,83.41,scattered clouds,-14.47,-48.46,Hotel Suinã
5,Yabrud,SY,86.00,overcast clouds,33.97,36.66,صالون مها حيدر - Salon Maha
11,Hermanus,ZA,77.00,clear sky,-34.42,19.23,Misty Waves Boutique Hotel
16,Bengkulu,ID,77.40,overcast clouds,-3.80,102.27,Grage Hotel Bengkulu
21,Victoria,HK,82.00,clear sky,22.29,114.16,Mini Hotel Central
...,...,...,...,...,...,...,...
563,Eyl,SO,84.69,clear sky,7.98,49.82,Amiin Hotel
564,Kilindoni,TZ,82.11,scattered clouds,-7.91,39.67,Bustani B&B
566,San Antonio,US,80.60,broken clouds,29.42,-98.49,Marriott Plaza San Antonio
567,Benjamin Hill,MX,81.00,broken clouds,30.17,-111.10,Luis Guillermo García Medina
569,Cam Ranh,VN,86.00,few clouds,11.92,109.16,OYO 598 Peony Hotel

In [34]:
len(hotel_df)

178

In [40]:
# Create the output file (CSV).
output_data_file = "weather_data/WeatherPy_vacation.csv"
# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")